global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml" # Adicione esta linha

scrape_configs:
  - job_name: 'delivery-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']